
spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  application:
    name: generatorinator
  #-------------------------------------------------------------------------------------------------
  # DATABASE
  #-------------------------------------------------------------------------------------------------
  datasource:
    # Postgres database
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:2489/generator
    username: generator
    password: generator
  # Database migrations
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    contexts: default
    database-change-log-table: ta_databasechangelog
    database-change-log-lock-table: ta_databasechangeloglock
  sql:
    init:
      mode: never
server:
  port: 8081
