version: "3.5"

services:
  db:
    image: docker.io/library/postgres:12
    restart: unless-stopped
    container_name: db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-generator}"
      POSTGRES_USER: "${POSTGRES_USER:-generator}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-generator}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

  generatorinator:
    image: 1grzyb1/generatorinator:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9999:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/generator"
      SPRING_DATASOURCE_USERNAME: "generator"
      SPRING_DATASOURCE_PASSWORD: "generator"

  frontend:
    image: 1grzyb1/generatorinator-frontend:latest
    restart: unless-stopped
    depends_on:
      - generatorinator
    ports:
      - "5173:5173"
    environment:
      PUBLIC_BACKEND_URL: "http://grzybek.snet.ovh:9999"

volumes:
  postgres-storage:
