name: Build and push docker

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login into docker registry
      uses: docker/login-action@v2.1.0
      with:
        username: 1grzyb1
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v4.0.0
    - name: Build and push Docker images
      run: docker build . --file Dockerfile --tag 1grzyb1/generatorinator
