name: Build and push docker

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login into docker registry
      uses: docker/login-action@v2.1.0
      with:
        username: 1grzyb1
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v4.0.0
    - name: Build and push Docker images
      with:
        context: .
        push: true
        tags: 1grzyb1/generatorinator:latest
